create database customercustomer_behaviour;

use customer_behaviour;

select * from customer limit 20;


-- Q1. What is the total revenue generated by male vs. female customers?

select gender, sum(purchase_amount) as revenue
from customer
group by gender;



-- Q2. Which customers used a discount but still spent more than the average purchase amount? 

select customer_id, purchase_amount 
from customer 
where discount_applied ='Yes' and  purchase_amount >= (select AVG(purchase_amount) from customer);



-- Q3. Which are the top 5 products with the highest average review rating?

select item_purchased,round(avg(review_rating),2) "Average_rate"
from customer
group by item_purchased
order by Average_rate  desc
limit 5;


-- Q4. Compare the average Purchase Amounts between Standard and Express Shipping. 

select round(avg(purchase_amount),2), shipping_type 
from customer
where shipping_type in ('Express','Standard')
group by shipping_type;


-- Q5. Do subscribed customers spend more? Compare average spend and total revenue 
-- between subscribers and non-subscribers.

select subscription_status,
count(customer_id),
avg(purchase_amount) "avg_spend",
sum(purchase_amount) "total_revanue"
from customer
group by subscription_status
order by total_revanue,avg_spend desc;




-- Q6. Which 5 products have the highest percentage of purchases with discounts applied?

select concat(round((purchase_amount*100/100)) ,'%') "Ak", discount_applied
from customer
group by item_purchased
order by Ak desc
limit 5;











